### ISSUE TITLE
Public Key Pinning should be configurable

### ISSUE THREAD

**Issue by rugk** [thorsteneckel/threema#1]
Does it use/support public key pinning?

Ref. https://github.com/rugk/threema-msgapi-sdk-php/issues/21, https://github.com/rugk/threema-msgapi-sdk-php/issues/49

**Comment by rugk** [comment]
Ah just saw https://github.com/thorsteneckel/threema/commit/acff602e33473bf30f829895c2885287bec1eb41, so you do support it? (Actually I think it should be configurable whether the user wants to use it or not)

**Comment by thorsteneckel** [comment]
[Yes](https://github.com/thorsteneckel/threema/blob/df086dfdb74fbf513d838632baf156ef61b52c3f/lib/threema/client.rb#L103), [it does](https://github.com/thorsteneckel/threema/blob/df086dfdb74fbf513d838632baf156ef61b52c3f/lib/threema/client.rb#L11) :) I'll add a configuration for disabling it but I will keep it active by default.

Regarding your comment on the commit: Actually I was a bit in a hurry but wanted to get the tests running 😇 I got an `Unauthorized` [exception in the Travis-CI run](https://travis-ci.org/thorsteneckel/threema/jobs/215260955#L991) which needs further investigation.

Thanks for your participation!

**Comment by thorsteneckel** [comment]
Done with the commit above.
