### ISSUE TITLE
Improve libsodium dependency

### ISSUE THREAD

**Issue by thorsteneckel** [thorsteneckel/threema#4]
This gem uses `rbnacl` which is a wrapper around [libsodium](https://github.com/jedisct1/libsodium) for doing the crypto stuff. Since this is an external dependency which makes CI tests and installation harder I decided to use the wrapped `rbnacl` gem alternative [rbnacl-libsodium](https://github.com/cryptosphere/rbnacl-libsodium) instead of relying on the availability of the library for now.

Since this is a possible attack vector and some might want to use their own `libsodium`both variations should be possible. Default should be own, fallback to wrapped. 

Commits:
- https://github.com/thorsteneckel/threema/commit/9b521f8ee6ea7a1f1d3198ede1ec95ad8aeaee50
- https://github.com/thorsteneckel/threema/commit/ef8b73a1c14aa808320feaf9d5deefe4f9a1401f

**Comment by roschaefer** [comment]
I guess this can be closed after #15

**Comment by thorsteneckel** [comment]
Right! Thanks for looking out 👀
