### ISSUE TITLE
Change bool pinning option to custom pinning string

### ISSUE THREAD

**Issue by rugk** [thorsteneckel/threema#9]
I'd suggest to let the user define the hashes to pin by themselves instead, when they e.g. want to pin the cert of a HTTPS MITM box or so or when you forget to update the hash when Threema updates their certs. :wink:

An example can be seen [here](https://github.com/rugk/threema-msgapi-sdk-php#creating-a-connection-with-advanced-options).

Ref https://github.com/thorsteneckel/threema/commit/5dfa6800628d25c052a62a539ed650a3bc7c15f1#commitcomment-21503456

**Comment by roschaefer** [comment]
I guess this can be closed after #24
